vich_uploader:
    db_driver: orm

    mappings:
        ingredient_image:
            uri_prefix: /images/ingredients
            upload_destination: '%kernel.project_dir%/public/images/ingredients'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        category_image:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
